### ISSUE TITLE
[question]: no peripheral available

### ISSUE THREAD

**Issue by zoologov** [marcomow/hass-addons#1]
### Description of the bug

Hey!
First, thanks for this add-on! 
I have one question, how did you connect to the toy? My bluetooth dongle doesn't see it (TP-Link UB4A supports BLE). I manually added it to known_devices.yaml, but the add-in writes "no peripheral available" in the logs.

> [s6-init] making user provided files available at /var/run/s6/etc exited 0.
[s6-init] ensuring user provided files have correct perms exited 0.
[fix-attrs.d] applying ownership & permissions fixes
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts
[cont-init.d] done.
[services.d] starting services
[services.d] done.
smartdot@0.0.1 start
NODE_ENV=production node src/index.js
Petoneer addon started!
poweredOn
> no peripheral available

### Steps To Reproduce

1. Go to "ha overview page"
2. Select "preset_small" in card with input_select.smartdot
3. In add-on logs "no peripheral available"

**Comment by marcomow** [comment]
Hi! The smartdot should be detected and connected automatically if it is discovered.

Sometimes this just fails and reboot of the addon is needed. Or the reboot of the smartdot in other cases. Please try both

Also, is the bluetooth advertised name of your device "PetCat"?

**Comment by zoologov** [comment]
In known_devices.yaml file I added:

![image](https://user-images.githubusercontent.com/1625074/152240576-5270b091-8707-488e-b5c1-27fe2f637525.png)

But in nRF App smartdot is:

![photo_2022-02-03_00-32-05](https://user-images.githubusercontent.com/1625074/152240886-00fd81dd-af16-49d6-986b-ebb4c3d83b3c.jpg)
![photo_2022-02-03_00-32-07](https://user-images.githubusercontent.com/1625074/152240888-96493f83-ed80-4312-87c3-92ec06888b48.jpg)
![photo_2022-02-03_00-32-09](https://user-images.githubusercontent.com/1625074/152240890-d43332f9-18cd-441a-84ae-11133666ea65.jpg)

**Comment by zoologov** [comment]
@marcomow, hi! Any idea?

**Comment by marcomow** [comment]
Thanks @zoologov for the detailed feedback!

I will add "TY" to the automatic detection of the new version so it should work out of the box also for you.

Also it should not be necessary to add the device to the known devices.

Finally please note that I'm working on a proper integration (not just an add-on) for the smart dot. It will take a bit of time so please be patient, but from there it should be way easier to set-up and use.

**Comment by marcomow** [comment]
fixed in https://github.com/marcomow/hass-addons/commit/f1e4d70b04983c366093685b91df1d1b7a4e7430
